language: node_js
node_js:
  - '9'
cache: yarn
services:
  - postgresql
before_script: psql -c 'create database travis_ci_test;' -U postgres
script: yarn test
after_success:
  - coveralls < coverage/lcov.info
