language: node_js
node_js:
  - '9'
cache: yarn
services:
  - mysql
before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS mptest;'
  - yarn run db:migrate
after_success:
  - coveralls < coverage/lcov.info
