language: node_js
node_js:
  - '9'
cache: yarn
services:
  - mysql
before_script:
  - mysql -u root -e 'CREATE DATABASE mptest;'
  - mysql -u root -e "CREATE USER 'musictravis'@'localhost' IDENTIFIED BY '12345';"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON mptest.* TO 'musictravis'@'localhost' WITH GRANT OPTION"
  - yarn run db:migrate
stage: teststage
script: yarn test
after_success:
  - coveralls < coverage/lcov.info
