language: node_js
node_js:
  - '9'
cache: yarn
services:
  - mysql
before_install:
  - mysql -e 'CREATE DATABASE mptest;'
before_script:
  - yarn run db:migrate
stage: teststage
script: yarn test
after_success:
  - coveralls < coverage/lcov.info
