language: node_js
node_js:
  - '9'
cache: yarn
services:
  - mysql
before_script:
  - mysql -e 'CREATE DATABASE music_playertest;'
  - yarn run db:migrate
stage: teststage
after_success:
  - coveralls < coverage/lcov.info
