language: node_js
node_js:
  - '9'
cache: yarn
services:
  - mysql
before_script:
  - mysql -u root -e 'CREATE DATABASE mpTest;'
  - mysql -u root -e "CREATE USER 'makler'@'localhost' IDENTIFIED BY 'makler';"
  - mysql -u root -e "GRANT ALL ON mpTest.* TO 'makler'@'localhost';"
stage: teststage
script: yarn test
after_success:
  - coveralls < coverage/lcov.info
