language: node_js
node_js:
  - '9'
cache: yarn
services:
  - mysql
before_script:
  - mysql -u root -e 'CREATE DATABASE mptest;'
  - mysql -u root -e "CREATE USER 'musictravis'@'localhost' IDENTIFIED BY 'musictravis';"
  - mysql -u root -e "GRANT ALL PRIVILEGES ON mptest.* TO 'musictravis'@'localhost';"

stage: teststage
script: yarn test
after_success:
  - coveralls < coverage/lcov.info
