language: node_js
node_js:
  - '9'
cache: yarn
services:
  - mysql
before_script:
  - sudo mysql -e "use mysql; update user set authentication_string=PASSWORD('12345') where User='ayotunde'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - sudo mysql_upgrade -u ayotunde -p12345
  - sudo service mysql restart
  - mysql -e 'CREATE DATABASE music_playertest;'
  - yarn run db:migrate
stage: teststage
script: yarn test
after_success:
  - coveralls < coverage/lcov.info
