language: node_js
node_js:
  - '9'
cache: yarn
services:
  - mysql
addons:
  apt:
    sources:
      - mysql-5.7-trusty
    packages:
      - mysql-server
      - mysql-client
before_install:
  - mysql -e "use mysql; update user set authentication_string=PASSWORD('new_password') where User='root'; update user set plugin='mysql_native_password';FLUSH PRIVILEGES;"
  - mysql_upgrade -u root -pnew_password
  - service mysql restart
before_script:
  - mysql -e 'CREATE DATABASE IF NOT EXISTS mptest;'
after_success:
  - coveralls < coverage/lcov.info
