language: node_js
node_js:
  - '9'
cache: yarn
services:
  - mysql
before_install:
  - echo "USE mysql;\nUPDATE user SET password=PASSWORD('12345') WHERE user='ayotunde';\nFLUSH PRIVILEGES;\n" | mysql -u ayotunde
    - mysql -e 'create database IF NOT EXISTS music_playertest;'
    - mysql -e "use music_playertest;"

before_script:
  - yarn run db:migrate
stage: teststage
script: yarn test
after_success:
  - coveralls < coverage/lcov.info
